### ISSUE TITLE
arcticfox-config won't see devices unless I change udev rules

### ISSUE THREAD

**Issue by febs** [hobbyquaker/arcticfox-config#25]
I had to install this udev rules file from another project in /etc/udev/rules.d/ 

https://github.com/Ban3/python-evic/blob/master/udev/99-nuvoton-hid.rules

Only then arcticfox-config could see my eleaf Aster.

Thank you

**Comment by hobbyquaker** [comment]
the `.deb` and `.rpm` packages are installing the udev rules automatically since v1.11.3
