### ISSUE TITLE
Debugger on npm start 

### ISSUE THREAD

**Issue by Dil3mm4** [hobbyquaker/arcticfox-config#27]
![schermata da 2017-09-03 21-35-34](https://user-images.githubusercontent.com/21145257/30006038-dce1d642-90ef-11e7-8f35-64bd8f550ab6.png)
That says all. :)

P.S. the icon is missing (in alt+tab and topbar).

System: Fedora 25 
DDE: Gnome 3

**Comment by hobbyquaker** [comment]
This is "works as designed" - Using it via `npm start` is meant for development. If you want to get rid of the debug console you should make a build - instructions can be found here: https://nfeteam.org/forum/threads/arcticfox-configuration-for-macos-and-linux.268/#post-1736

**Comment by Dil3mm4** [comment]
Thanks for the info.
