### ISSUE TITLE
Plans for a firmware uploader?

### ISSUE THREAD

**Issue by dbuezas** [hobbyquaker/arcticfox-config#28]
for some reason my virtual box fails uploading the firmware in both my pico 75w and pico 25, so this would be great! :)

**Comment by hobbyquaker** [comment]
This is not possible - the firmware update mechanism is closed source and the makers of Arcticfox/NFE Tools don't want to make it public.

**Comment by febs** [comment]
Actually it is possible to upload the firmware to the Picos with this tool 
https://github.com/Ban3/python-evic

So I guess it'd be possible to build a GUI around it :-D

**Comment by Dil3mm4** [comment]
@febs they aren't the same.

**Comment by febs** [comment]
Ouch. I used it to upload the official firmware, so I assumed the format would be the same.
