### ISSUE TITLE
MAC OS X Java Error 

### ISSUE THREAD

**Issue by bluedreamin** [hobbyquaker/arcticfox-config#40]
![image](https://user-images.githubusercontent.com/34849596/34346620-e6b90652-e9cf-11e7-8b0c-76baf5ece5c3.png)

Doesn't let me upload, download, or find any new firmware versions for RX300 (or anything I think).

**Comment by pjalm** [comment]
I have same issue with my Predator 228

**Comment by pjalm** [comment]
I got it working, you can't use this to flash firmware its only a config tool so your device requires you flash it first on a windows machine
