### ISSUE TITLE
error on connecting with stock-firmware device

### ISSUE THREAD

**Issue by byaka** [hobbyquaker/arcticfox-config#43]
Hola. i have new device with stock wirmware and want to change it to ArcticFox. But dont have windows so i founded this awesome project. After installing, adding me to udev group and relogin i have this

![image](https://user-images.githubusercontent.com/1580811/36566479-a7ca9062-1834-11e8-8ace-e8c6dce00464.png)

so it something wrong or i cant change firmfare with this tool?

**Comment by hobbyquaker** [comment]
You can't flash firmware with this project, and you can only connect devices that already have an arcticfox firmware. This is due to the closed source nature of the firmware-flash part of the NFE tools, nfeteam doesn't want to make the firmware flash procedure public (as of today at least).
